name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 2.6, 2.5, 2.4]
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        ruby -e "Dir['{,spec/**/}Gemfile.lock'].each { |f| File.write(f, File.read(f).split('BUNDLED WITH').first)}"
        bundle install
    - name: Change TMPDIR to something non symlinked
      run: |
        echo "::set-env name=TMPDIR::$HOME/tmp"
        mkdir $HOME/tmp
    - name: Run test
      run: bundle exec rake
