# frozen_string_literal: true
source 'https://rubygems.org'

rails_version = '6.1.3'

gem 'actioncable', rails_version
gem 'actionmailer', rails_version
gem 'actionpack', rails_version
gem 'actionview', rails_version
gem 'activejob', rails_version
gem 'activemodel', rails_version
gem 'activerecord', rails_version
gem 'activesupport', rails_version
gem 'railties', rails_version
gem 'sprockets-rails'

gem 'sqlite3', '~> 1.7.3' # last before 2.0
gem 'tzinfo-data'
gem 'parallel_tests', path: "../../../", group: :development
